//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchCQRSandMediator.Application.Resources.Organizations.Commands.CreateOrganization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CreateOrganizationCommandValidator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateOrganizationCommandValidator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CleanArchCQRSandMediator.Application.Resources.Organizations.Commands.CreateOrgan" +
                            "ization.CreateOrganizationCommandValidator", typeof(CreateOrganizationCommandValidator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máximo {0} caracteres..
        /// </summary>
        internal static string Validation_Description_MaxLength {
            get {
                return ResourceManager.GetString("Validation_Description_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mínimo {0} caracteres..
        /// </summary>
        internal static string Validation_Description_MinLength {
            get {
                return ResourceManager.GetString("Validation_Description_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La descripción es obligatoria..
        /// </summary>
        internal static string Validation_Description_Required {
            get {
                return ResourceManager.GetString("Validation_Description_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máximo {0} caracteres..
        /// </summary>
        internal static string Validation_Name_MaxLength {
            get {
                return ResourceManager.GetString("Validation_Name_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mínimo {0} caracteres..
        /// </summary>
        internal static string Validation_Name_MinLength {
            get {
                return ResourceManager.GetString("Validation_Name_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre es obligatorio..
        /// </summary>
        internal static string Validation_Name_Required {
            get {
                return ResourceManager.GetString("Validation_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El slug solo puede contener letras minúsculas, números y guiones intermedios, y debe tener una longitud de entre 3 y 39 caracteres..
        /// </summary>
        internal static string Validation_Slug_Pattern {
            get {
                return ResourceManager.GetString("Validation_Slug_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El slug es obligatorio..
        /// </summary>
        internal static string Validation_Slug_Required {
            get {
                return ResourceManager.GetString("Validation_Slug_Required", resourceCulture);
            }
        }
    }
}
